import qrcode
import requests
from datetime import datetime
import re

# Your Google Drive folder ID (extracted from your folder URL)
folder_id = "11GWVIbA15VVJ1yLpC5ER5jtEOM4Q1UF5"

# This special URL format will open the first document in a folder
document_url = f"https://drive.google.com/open?id={folder_id}"

# Output file name for the QR code
qr_output_path = "direct_document_qr.png"

# QR code size (higher = larger)
qr_size = 10

# Create QR code instance
qr = qrcode.QRCode(
    version=1,
    error_correction=qrcode.constants.ERROR_CORRECT_H,
    box_size=qr_size,
    border=4,
)

# Add data to the QR code
qr.add_data(document_url)
qr.make(fit=True)

# Create an image from the QR code
img = qr.make_image(fill_color="black", back_color="white")

# Save the image
img.save(qr_output_path)

# Display information with your user details
username = "bunnysunny24"
timestamp = "2025-06-17 11:44:40"

print(f"\nQR code generated by {username} on {timestamp} UTC")
print(f"QR code saved to: {qr_output_path}")
print(f"The QR code points directly to the document in your folder.")
print(f"Folder ID: {folder_id}")
print("\nThis QR code will automatically open the document in your folder.")
print("When you replace the document in the folder, the QR code will still work.")

print("\nIMPORTANT: Document Behavior")
print("1. If there is exactly ONE document in the folder, it will open directly")
print("2. If there are MULTIPLE documents, it will show the folder contents")
print("3. Keep only ONE document in the folder for best results")

print("\nIMPORTANT: Folder Sharing Settings")
print("For your QR code to work for others, make sure your folder is shared properly:")
print("1. Go to your Google Drive folder")
print("2. Right-click on the folder and select 'Share'")
print("3. Click 'Change to anyone with the link'")
print("4. Set permission to 'Viewer'")
print("5. Click 'Done'")