import qrcode
from datetime import datetime

def generate_folder_qr(folder_url, qr_output_path="drive_folder_qr.png", qr_size=10):
    """Generate a QR code that links to a Google Drive folder"""
    # Create QR code instance
    qr = qrcode.QRCode(
        version=1,
        error_correction=qrcode.constants.ERROR_CORRECT_H,
        box_size=qr_size,
        border=4,
    )
    
    # Add data to the QR code
    qr.add_data(folder_url)
    qr.make(fit=True)
    
    # Create an image from the QR code
    img = qr.make_image(fill_color="black", back_color="white")
    
    # Save the image
    img.save(qr_output_path)
    
    # Current information
    username = "bunnysunny24"
    timestamp = "2025-06-17 11:39:09"
    
    print(f"\nQR code generated by {username} on {timestamp} UTC")
    print(f"QR code saved to: {qr_output_path}")
    print(f"The QR code points to your Google Drive folder: {folder_url}")
    print("\nHow this works:")
    print("1. The QR code will always open your Google Drive folder")
    print("2. You can add, remove, or update documents in the folder anytime")
    print("3. Users will always see the latest content when they scan the QR")
    print("4. Make sure your folder sharing settings allow viewers to access")
    
    return True

if __name__ == "__main__":
    print("Create a permanent QR code for your Google Drive folder")
    print("Current Date and Time (UTC): 2025-06-17 11:39:09")
    print("Current User: bunnysunny24")
    
    # Get folder URL
    folder_url = input("\nEnter your Google Drive folder URL: ")
    
    if not folder_url:
        print("Error: You must provide a Google Drive folder URL.")
    else:
        generate_folder_qr(folder_url)
        
        print("\nIMPORTANT: Folder Sharing Settings")
        print("For your QR code to work for others, make sure your folder is shared properly:")
        print("1. Go to your Google Drive folder")
        print("2. Right-click on the folder and select 'Share'")
        print("3. Click 'Change to anyone with the link'")
        print("4. Set permission to 'Viewer'")
        print("5. Click 'Done'")