import qrcode
from datetime import datetime

# Your Google Drive folder URL (this will remain constant)
folder_url = "https://drive.google.com/drive/folders/11GWVIbA15VVJ1yLpC5ER5jtEOM4Q1UF5?usp=drive_link"

# Output file name for the QR code
qr_output_path = "drive_folder_qr.png"

# QR code size (higher = larger)
qr_size = 10

# Create QR code instance
qr = qrcode.QRCode(
    version=1,
    error_correction=qrcode.constants.ERROR_CORRECT_H,
    box_size=qr_size,
    border=4,
)

# Add data to the QR code
qr.add_data(folder_url)
qr.make(fit=True)

# Create an image from the QR code
img = qr.make_image(fill_color="black", back_color="white")

# Save the image
img.save(qr_output_path)

# Display information with your user details
username = "bunnysunny24"
timestamp = "2025-06-17 11:42:27"

print(f"\nQR code generated by {username} on {timestamp} UTC")
print(f"QR code saved to: {qr_output_path}")
print(f"The QR code points to your Google Drive folder: {folder_url}")
print("\nThis QR code will always take users to your folder which contains the document.")
print("You can replace the document in the folder anytime without changing the QR code.")

print("\nIMPORTANT: Folder Sharing Settings")
print("For your QR code to work for others, make sure your folder is shared properly:")
print("1. Go to your Google Drive folder")
print("2. Right-click on the folder and select 'Share'")
print("3. Click 'Change to anyone with the link'")
print("4. Set permission to 'Viewer'")
print("5. Click 'Done'")