import qrcode
import requests
from datetime import datetime

def create_tinyurl(url):
    """Create a TinyURL shortlink"""
    response = requests.get(f"https://tinyurl.com/api-create.php?url={url}")
    if response.status_code == 200:
        return response.text
    else:
        return None

# Your current Google Drive document URL
document_url = "https://drive.google.com/file/d/1eM6RTY0fyS5lijjuiz7ys77JT4c3R2Fv/view"

# Output file name for the QR code
qr_output_path = "updatable_document_qr.png"

# QR code size (higher = larger)
qr_size = 10

# Create a TinyURL for the document
tiny_url = create_tinyurl(document_url)

if not tiny_url:
    print("Failed to create TinyURL. Please check your internet connection.")
else:
    # Create QR code instance
    qr = qrcode.QRCode(
        version=1,
        error_correction=qrcode.constants.ERROR_CORRECT_H,
        box_size=qr_size,
        border=4,
    )
    
    # Add data to the QR code
    qr.add_data(tiny_url)
    qr.make(fit=True)
    
    # Create an image from the QR code
    img = qr.make_image(fill_color="black", back_color="white")
    
    # Save the image
    img.save(qr_output_path)
    
    # Display information with user details
    username = "bunnysunny24"
    timestamp = "2025-06-17 11:47:29"
    
    print(f"\nQR code generated by {username} on {timestamp} UTC")
    print(f"QR code saved to: {qr_output_path}")
    print(f"The QR code points to this TinyURL: {tiny_url}")
    print(f"The TinyURL currently redirects to: {document_url}")
    
    print("\n==== VERY IMPORTANT - HOW TO UPDATE YOUR DOCUMENT ====")
    print("To update the document without changing the QR code:")
    print("1. Create your new document in Google Drive and get its sharing link")
    print("2. Visit: https://tinyurl.com/app/")
    print("3. Create a free account (if you haven't already)")
    print("4. In your TinyURL dashboard, click 'Claim URL'")
    print(f"5. Enter your TinyURL: {tiny_url.replace('https://tinyurl.com/', '')}")
    print("6. Once claimed, you can edit it to point to your new document link")
    print("7. Save changes and your QR code will now open the new document")
    print("\nSAVE THESE INSTRUCTIONS! You'll need them when updating your document.")
    